vpn_template_name: 'DC-vEdge-VPN30'
ospf_template_name: 'DC-VPN30-OSPF'
vpn_interface_template_name: 'DC-VPN30-Interface-Template'
service_vpn_id: '30'
service_vpn_interface_id: 'loopback100'
interface_ip_address: '10.2.10.250/24'
ospf_router_id: '10.2.0.2'
vpn_default_gw: '10.1.10.1'
ospf_area_number: '0'
ospf_interface: 'ge0/0'
